config/routes.rb
Rails.application.routes.draw do
  resources :flats
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'flats#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  # GET /flats
  # GET /flats.json
  def index
    @flats = Flat.all
  end

  # GET /flats/1
  # GET /flats/1.json
  def show
  end

  # GET /flats/new
  def new
    @flat = Flat.new
  end

  # GET /flats/1/edit
  def edit
  end

  # POST /flats
  # POST /flats.json
  def create
    @flat = Flat.new(flat_params)

    respond_to do |format|
      if @flat.save
        format.html { redirect_to @flat, notice: 'Flat was successfully created.' }
        format.json { render :show, status: :created, location: @flat }
      else
        format.html { render :new }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flats/1
  # PATCH/PUT /flats/1.json
  def update
    respond_to do |format|
      if @flat.update(flat_params)
        format.html { redirect_to @flat, notice: 'Flat was successfully updated.' }
        format.json { render :show, status: :ok, location: @flat }
      else
        format.html { render :edit }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flats/1
  # DELETE /flats/1.json
  def destroy
    @flat.destroy
    respond_to do |format|
      format.html { redirect_to flats_url, notice: 'Flat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flat
      @flat = Flat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flat_params
      params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= form_with(model: flat, local: true) do |form| %>
  <% if flat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flat.errors.count, "error") %> prohibited this flat from being saved:</h2>

      <ul>
      <% flat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price_per_night %>
    <%= form.number_field :price_per_night %>
  </div>

  <div class="field">
    <%= form.label :number_of_guests %>
    <%= form.number_field :number_of_guests %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/flats/edit.html.erb
<h1>Editing Flat</h1>

<%= render 'form', flat: @flat %>

<%= link_to 'Show', @flat %> |
<%= link_to 'Back', flats_path %>

app/views/flats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All our Flats</h1>
<h6>We found <%= @flats.length %> flats on our website.</h6>

<div class="row">
  <% @flats.each do |flat| %>
    <div class="col-xs-4">
      <div class="card">
        <img src="https://picsum.photos/200/300/?random" class="card-img-top" alt="amazing pic">
        <div class="card-body">
          <h5 class="card-title"><%= flat.name %></h5>
          <p class="card-text"><%= flat.address %></p>
          <div class="flex">
            <div class="flex">
              <i class="fas fa-users"></i>
              <%= flat.number_of_guests %>
            </div>
            <div class="flex">
              <i class="fas fa-euro-sign"></i>
              <%= flat.price_per_night %>
            </div>
          </div>
        </div>
        <div class="card-footer">
          <%= link_to 'More info', flat, class: 'card-link' %>
          <%= link_to 'Edit', edit_flat_path(flat), class: 'card-link' %>
          <%= link_to 'Remove', flat, method: :delete, data: { confirm: 'Are you sure?' }, class: 'card-link' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<br>

<%= link_to 'New Flat', new_flat_path %>

app/views/flats/new.html.erb
<h1>New Flat</h1>

<%= render 'form', flat: @flat %>

<%= link_to 'Back', flats_path %>

app/views/flats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @flat.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @flat.address %>
</p>

<p>
  <strong>Description:</strong>
  <%= @flat.description %>
</p>

<p>
  <strong>Price per night:</strong>
  <%= @flat.price_per_night %>
</p>

<p>
  <strong>Number of guests:</strong>
  <%= @flat.number_of_guests %>
</p>

<%= link_to 'Edit', edit_flat_path(@flat) %> |
<%= link_to 'Back', flats_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css" integrity="sha384-PDle/QlgIONtM1aqA2Qemk5gPOE7wFq8+Em+G/hmo5Iq0CCmYZLv3fVRDJ4MMwEA" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>